language: python

addons:
  apt:
    packages:
    - swig
    - libssl-dev
    - libssl1.0.0
    - python-setuptools
    - python-twisted

sudo: false

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
matrix:
  allow_failures:
    - python: 3.3
    - python: 3.4

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then travis_retry pip install Twisted==15.0.0 ; else travis_retry pip install Twisted ; fi
  - python setup.py install

script: python setup.py test
